services:
  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 5s

  sender:
    build: .
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBIT__HOST: rabbitmq
      RABBIT__PORT: "5672"
      RABBIT__USER: guest
      RABBIT__PASS: guest
      RABBIT__EXCHANGE: mail.send
      RABBIT__QUEUE: mail.send.q
      RABBIT__ROUTINGKEY: send
      RABBIT__CONSUMERS: "1"
      RABBIT__PREFETCH: "1"

      SMTP_HOST: smtp.yandex.ru
      SMTP_PORT: "587"
      SMTP_USER: petrchurakov@yandex.ru
      SMTP_PASS: pjojfbklywnoeasw
      SMTP_FROM_NAME: MailSender Test
      SMTP_FROM_EMAIL: petrchurakov@yandex.ru
      SMTP_USE_STARTTLS: "true"

      IDEM_FILE: data/processed-ids.log
    volumes:
      - sender-data:/app/data

volumes:
  sender-data:
